import { Content } from './content.model';

export interface EntryPokemon {
    gsx$dexno: Content;
    gsx$name: Content;
    gsx$form: Content;
    gsx$nickname: Content;
    gsx$gender: Content;
    gsx$shiny: Content;
    gsx$nature: Content;
    gsx$statnature: Content;
    gsx$ability: Content;
    gsx$hpiv: Content;
    gsx$atkiv: Content;
    gsx$defiv: Content;
    gsx$spaiv: Content;
    gsx$spdiv: Content;
    gsx$speiv: Content;
    gsx$hpht: Content;
    gsx$atkht: Content;
    gsx$defht: Content;
    gsx$spaht: Content;
    gsx$spdht: Content;
    gsx$speht: Content;
    gsx$hpev: Content;
    gsx$atkev: Content;
    gsx$defev: Content;
    gsx$spaev: Content;
    gsx$spdev: Content;
    gsx$speev: Content;
    gsx$move1: Content;
    gsx$move2: Content;
    gsx$move3: Content;
    gsx$move4: Content;
    gsx$eggmove1: Content;
    gsx$eggmove2: Content;
    gsx$eggmove3: Content;
    gsx$eggmove4: Content;
    gsx$ball: Content;
    gsx$helditem: Content;
    gsx$ot: Content;
    gsx$tid: Content;
    gsx$language: Content;
    gsx$origingame: Content;
    gsx$notes: Content;
}
