name: CI

on:
  push:
    branches: [ main, develop, feature/*]
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          args: >
            -Dsonar.organization=sotam
            -Dsonar.projectKey=Sotam_CollectionSheet
            -Dsonar.projectVersion=${GITHUB_SHA}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src/app
            -Dsonar.exclusions='**/node_modules/**,**/*.spec.ts'
            -Dsonar.tests=src/app
            -Dsonar.test.inclusions=**/*.spec.ts
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
