name: CI

on:
  push:
    branches-ignore: [ main ]
    tags-ignore: [ '**' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 14.x

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci
      
      - name: Build solution
        run: ng build --prod --output-path=dist --base-href="https://collectionsheet.wilbrink.dev/"

      - name: Test
        run: npm test -- --configuration=ci --code-coverage --watch=false

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/report-lcovonly
          fail_ci_if_error: true
          verbose: true
