name: CICD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 14.x

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci
      
      - name: Build solution
        run: ng build --prod --output-path=dist --base-href="https://sotam.github.io/CollectionSheet/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
